apiVersion: v1
kind: Secret
metadata:
  name: pub-cmd-msg-secret
  namespace: {{ .Values.namespace }}
data:
{{ if .Values.dapr }}
  redis-password: {{ .Values.redis.password }}
{{ end }}
{{ if .Values.dapr.azureStorage }}
  azure-storage-account-key: {{ .Values.dapr.azureStorage.accountKey }}
{{ end }}
